# version format
version: uwx-nightly-{build}

# Build worker image (VM template)
image: Visual Studio 2017

clone_folder: c:\projects\dsp

clone_script:
- cmd: git clone -q --recursive --branch=%APPVEYOR_REPO_BRANCH% https://github.com/uwx/HSNXT.Extensions.git %APPVEYOR_BUILD_FOLDER%
- cmd: git checkout -qf %APPVEYOR_REPO_COMMIT%

branches:
  only:
    - master

environment:
  access_token:
    secure: ZCGkDJawCLuRgzYTYraor3+u8xB5hjlMC2RhZZYWKkAVWbJ8DBI/ws7qqpZ2c2L1

install:
  - cmd: appveyor downloadfile https://dist.nuget.org/win-x86-commandline/v4.3.0/nuget.exe

before_build:
  - cmd: nuget sources add -Name dsp-myget -Source https://www.myget.org/F/dsharpplus-nightly/api/v3/index.json
  - cmd: nuget restore
  - ps: Install-Product node 8

build: off

build_script:
  - ps: dotnet build "TestProject.sln" -c Release
  - ps: dotnet publish "TestProject.sln" --configuration Release -f net47
  - ps: dotnet publish "HSNXT.Extensions/HSNXT.Extensions.csproj" -c Release -f netstandard2.0
  - ps: dotnet pack "HSNXT.Extensions/HSNXT.Extensions.csproj" -c Release -o "Proj1" --no-build

artifacts:
  - path: "**\\*.nupkg"
  
  - path: "**\\bin\\Release\\net47\\*.dll"
    name: Release DLLs (.NET 4.7)
    type: zip
  - path: "**\\bin\\Release\\netcoreapp2.0\\*.dll"
    name: Release DLLs (.NET Core 2.0)
    type: zip

# Automatically register private account and/or project AppVeyor NuGet feeds.
nuget:
  account_feed: false
  project_feed: false
  disable_publish_on_pr: true     # disable publishing of .nupkg artifacts to account/project feeds for pull request builds

deploy:
  - provider: NuGet
    skip_symbols: false
    api_key:
      secure: ZkuAOJwTjYBiEAHrTHkVDYaNRBaWDDmvpkUVN+9PnsHWQnfDDdDWWAMPltRlYNYn
      
notifications:
  - provider: Slack
    on_build_success: true
    on_build_failure: true
    incoming_webhook:
      secure: /tQzfO0uCSjCMZF2eqIdIGAxeA/Zyn2eKDJKfcnvwV7PsWf0sLZolUFnbnWva3KWtNuYgOXz30QpuRl/fcza4Kp7Ymg7COchmmFXpAPu+ZW/yuY4SiEEgTIRmpLZZFLVlFPOlb+9+JjNvk2Ck6LnWD799g3ErcK7arpJF7O0CrK3Bs/Ib3Qeyigdu7g71Lva